markdown: kramdown
google_analytics:
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
markdown: kramdown
show_downloads: false
github_username: LahaLuhm
twitter_username: Mguy13

title: Personal Page of Laha Luhem
email: t3mp0rary13@gmail.com
description: Happy digging!

plugins:
  - jemoji
  - jekyll-include-cache
