markdown: kramdown
google_analytics:
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: kramdown
show_downloads: false
github_username: LahaLuhm
twitter_username: Mguy13

title: Personal Page of Laha Luhem
email: t3mp0rary13@gmail.com
description: Happy digging!
