markdown: kramdown
google_analytics:
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
markdown: kramdown
show_downloads: false
github_username: LahaLuhm
twitter_username: Mguy13

title: Personal Page of Laha Luhem
name: "Laha Luhem"
subtitle: ""
description: Happy digging!
email: t3mp0rary13@gmail.com

breadcrumbs: true  # disabled by default

plugins:
  - jekyll-include-cache
